// <auto-generated />
using System;
using FaultDetection.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaultDetection.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260421145813_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FaultDetection.Web.Models.InspectionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaultType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRepaired")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("TowerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InspectionLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConfidenceScore = 0.98f,
                            CreatedDate = new DateTime(2026, 4, 21, 12, 58, 12, 360, DateTimeKind.Utc).AddTicks(3189),
                            FaultType = "Bình thường",
                            ImagePath = "/images/sample_ok.jpg",
                            IsRepaired = false,
                            Latitude = 21.028500000000001,
                            Longitude = 105.85420000000001,
                            TowerId = "T-110KV-01"
                        },
                        new
                        {
                            Id = 2,
                            ConfidenceScore = 0.85f,
                            CreatedDate = new DateTime(2026, 4, 21, 13, 58, 12, 360, DateTimeKind.Utc).AddTicks(3819),
                            FaultType = "Sứ nứt",
                            ImagePath = "/images/sample_fault.jpg",
                            IsRepaired = false,
                            Latitude = 21.0305,
                            Longitude = 105.8522,
                            TowerId = "T-110KV-02"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
